name: aram_ai_analyzer
description: Personal ARAM match analysis app using Riot and OpenAI APIs.
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_secure_storage: ^10.3.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
